title: "Die Seite zur Pilz-Chronik"
description: "Ergänzungen, Errata und digitale Inhalte zur gedruckten Pilz-Chronik."
url: "https://pilzchronik.github.io"
baseurl: "/bonusseite"

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - downloads.md
  - karte.md
  - links.md
