title: "Die Seite zur Pilz-Chronik"
description: "Ergänzungen, Errata und digitale Inhalte zur gedruckten Pilz-Chronik."
url: "https://pilzchronik.github.io"
baseurl: "/bonusseite"

theme: minima
plugins:
  - jekyll-feed

# Navigation exakt steuern:
header_pages:
  - downloads.md
  - karte.md
  - links.md
  - errata.md
  - kontakt.md
