title: "Die Seite zur Pilz-Chronik"
description: "Ergänzungen, Errata und digitale Inhalte zur gedruckten Pilz-Chronik."
url: "https://pilzchronik.github.io"
baseurl: "/bonusseite"

theme: minima
plugins:
  - jekyll-feed

# Navigation (Start/Über nicht in der Navi)
header_pages:
  - downloads.md
  - karte.md
  - links.md
  - kontakt.md

# Auszüge im Änderungslog anzeigen
show_excerpts: true
